<?php
/**
 * Plugin Name: WordPress Navigation
 * Plugin URI:  https://github.com/joen/wordpress-navigation
 * Description: A rethought left navigation for the WordPress admin.
 * Version:     0.1.0
 * Author:      Joen Asmussen
 * License:     GPL-2.0-or-later
 * Text Domain: wordpress-navigation
 */

defined( 'ABSPATH' ) || exit;

class WP_Navigation {

	public function __construct() {
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue' ] );
		add_action( 'admin_head',            [ $this, 'inject_scheme_vars' ] );
		add_action( 'admin_footer',          [ $this, 'output_data' ], 1 );
		add_action( 'rest_api_init',         [ $this, 'register_rest_routes' ] );
	}

	/**
	 * REST API routes for reading and writing per-user favorites.
	 */
	public function register_rest_routes() {
		register_rest_route( 'wn/v1', '/favorites', [
			[
				'methods'             => 'GET',
				'callback'            => [ $this, 'rest_get_favorites' ],
				'permission_callback' => fn() => is_user_logged_in(),
			],
			[
				'methods'             => 'POST',
				'callback'            => [ $this, 'rest_add_favorite' ],
				'permission_callback' => fn() => is_user_logged_in(),
				'args'                => [
					'slug'  => [ 'required' => true, 'sanitize_callback' => 'sanitize_text_field' ],
					'label' => [ 'required' => true, 'sanitize_callback' => 'sanitize_text_field' ],
					'icon'  => [ 'required' => true, 'sanitize_callback' => 'sanitize_text_field' ],
				],
			],
		] );

		register_rest_route( 'wn/v1', '/favorites/(?P<slug>[^/]+)', [
			'methods'             => 'DELETE',
			'callback'            => [ $this, 'rest_delete_favorite' ],
			'permission_callback' => fn() => is_user_logged_in(),
		] );
	}

	public function rest_get_favorites(): WP_REST_Response {
		return rest_ensure_response( $this->get_user_favorites() );
	}

	public function rest_add_favorite( WP_REST_Request $req ): WP_REST_Response {
		$favs = $this->get_user_favorites();
		$slug = $req->get_param( 'slug' );

		// Idempotent — only add if not already present.
		foreach ( $favs as $f ) {
			if ( $f['slug'] === $slug ) {
				return rest_ensure_response( $f );
			}
		}

		$new    = [
			'slug'  => $slug,
			'label' => $req->get_param( 'label' ),
			'icon'  => $req->get_param( 'icon' ),
		];
		$favs[] = $new;
		$this->save_user_favorites( $favs );
		return rest_ensure_response( $new );
	}

	public function rest_delete_favorite( WP_REST_Request $req ): WP_REST_Response {
		$slug = urldecode( $req->get_param( 'slug' ) );
		$favs = array_values( array_filter(
			$this->get_user_favorites(),
			fn( $f ) => $f['slug'] !== $slug
		) );
		$this->save_user_favorites( $favs );
		return rest_ensure_response( [ 'deleted' => true ] );
	}

	private function get_user_favorites(): array {
		$raw     = get_user_meta( get_current_user_id(), 'wn_favorites', true );
		$decoded = json_decode( $raw ?: '[]', true );
		return is_array( $decoded ) ? $decoded : [];
	}

	private function save_user_favorites( array $favs ): void {
		update_user_meta( get_current_user_id(), 'wn_favorites', wp_json_encode( $favs ) );
	}

	/**
	 * Read the current user's WP color scheme and inject its values as CSS
	 * custom properties so the nav inherits the right colors automatically.
	 */
	public function inject_scheme_vars() {
		global $_wp_admin_css_colors;

		$slug   = get_user_option( 'admin_color' ) ?: 'fresh';
		$scheme = $_wp_admin_css_colors[ $slug ] ?? ( $_wp_admin_css_colors['fresh'] ?? null );

		if ( ! $scheme || empty( $scheme->colors ) ) {
			return;
		}

		$c        = $scheme->colors;
		$icons    = (array) ( $scheme->icon_colors ?? [] );
		$sanitize = fn( $v ) => preg_match( '/^#[0-9a-f]{3,8}$/i', $v ) ? esc_attr( $v ) : null;

		$vars = array_filter( [
			// colors[0] = primary sidebar background for the current scheme.
			'--wn-scheme-bg'      => $sanitize( $c[0] ?? '' ),
			// colors[2] = accent / active-item highlight.
			'--wn-scheme-accent'  => $sanitize( $c[2] ?? '' ),
			// icon_colors.base = default icon/text colour on the dark bg.
			// icon_colors.current = text colour on the active (accent) bg.
			'--wn-scheme-icon'    => $sanitize( $icons['base']    ?? '' ),
			'--wn-scheme-current' => $sanitize( $icons['current'] ?? '' ),
		] );

		if ( empty( $vars ) ) {
			return;
		}

		$decls = implode( '; ', array_map(
			fn( $k, $v ) => "$k: $v",
			array_keys( $vars ),
			$vars
		) );

		echo "<style>:root { $decls }</style>\n";
	}

	public function enqueue() {
		$plugin_url  = plugin_dir_url( __FILE__ );
		$plugin_path = plugin_dir_path( __FILE__ );

		// Use the asset file generated by @wordpress/scripts if available.
		$asset_file = $plugin_path . 'build/index.asset.php';
		$asset      = file_exists( $asset_file )
			? require $asset_file
			: [ 'dependencies' => [ 'wp-element' ], 'version' => '0.1.0' ];

		wp_enqueue_script(
			'wn-nav',
			$plugin_url . 'build/index.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		$css_path = $plugin_path . 'build/style-index.css';
		if ( file_exists( $css_path ) ) {
			wp_enqueue_style(
				'wn-nav',
				$plugin_url . 'build/style-index.css',
				[],
				$asset['version']
			);
		}
	}

	/**
	 * Output menu data as a global JS variable before footer scripts run.
	 * Priority 1 ensures this fires before wp_print_footer_scripts (priority 20).
	 */
	public function output_data() {
		global $menu, $submenu, $pagenow;

		$config     = $this->get_config();
		$menu_items = $this->clean_item_children(
			$this->collect_menu( $menu, $submenu ),
			$config
		);

		$data = [
			'menuItems'   => $menu_items,
			'config'      => $config,
			'currentPage' => [
				'file'     => $pagenow ?? '',
				'page'     => sanitize_text_field( $_GET['page']      ?? '' ),
				'postType' => sanitize_text_field( $_GET['post_type'] ?? '' ),
				'taxonomy' => sanitize_text_field( $_GET['taxonomy']  ?? '' ),
			],
			'adminUrl'    => admin_url(),
			'favorites'   => $this->get_user_favorites(),
			'restUrl'     => rest_url( 'wn/v1/' ),
			'restNonce'   => wp_create_nonce( 'wp_rest' ),
		];

		echo '<script>window.wnNavData = ' . wp_json_encode( $data ) . ';</script>' . "\n";
	}

	private function collect_menu( $menu, $submenu ) {
		$items = [];

		if ( ! is_array( $menu ) ) {
			return $items;
		}

		foreach ( $menu as $position => $entry ) {
			if ( empty( $entry[2] ) ) {
				continue;
			}
			if ( isset( $entry[4] ) && strpos( $entry[4], 'wp-menu-separator' ) !== false ) {
				continue;
			}

			$slug = $entry[2];
			$item = [
				'slug'     => $slug,
				'label'    => $this->clean_label( $entry[0] ),
				'cap'      => $entry[1],
				'url'      => $this->resolve_url( $slug ),
				'icon'     => $entry[6] ?? '',
				'position' => (int) $position,
				'children' => [],
			];

			if ( isset( $submenu[ $slug ] ) && is_array( $submenu[ $slug ] ) ) {
				foreach ( $submenu[ $slug ] as $sub_pos => $sub ) {
					if ( empty( $sub[2] ) ) {
						continue;
					}
					$item['children'][] = [
						'slug'     => $sub[2],
						'label'    => $this->clean_label( $sub[0] ),
						'cap'      => $sub[1],
						'url'      => $this->resolve_url( $sub[2], $slug ),
						'position' => (int) $sub_pos,
					];
				}
			}

			$items[] = $item;
		}

		return $items;
	}

	/**
	 * Clean up children for every menu item:
	 *  1. stripAll  — wipe all children (e.g. Dashboard; removes Updates).
	 *  2. Add-new   — promote "Add New" children to addNewUrl; remove from list.
	 *  3. Self-ref  — drop children whose slug === parent slug ("All Posts" under Posts).
	 *  4. exclude   — drop additional slugs listed in nav-config childFilters.
	 */
	private function clean_item_children( array $items, array $config ) {
		$filters = $config['childFilters'] ?? [];

		return array_map( function ( $item ) use ( $filters ) {
			$parent_slug = $item['slug'];
			$filter      = $filters[ $parent_slug ] ?? [];

			// stripAll wins everything — no children, no + button.
			if ( ! empty( $filter['stripAll'] ) ) {
				$item['children'] = [];
				return $item;
			}

			$children    = [];
			$add_new_url = null;

			foreach ( $item['children'] as $child ) {
				// Promote "Add New" items to a + button.
				if ( $this->is_add_new_item( $child ) ) {
					$add_new_url = $child['url'];
					continue;
				}
				// Drop self-referential children ("All Posts" slug === "edit.php" parent).
				if ( $child['slug'] === $parent_slug ) {
					continue;
				}
				$children[] = $child;
			}

			// Apply any additional exclude rules from config.
			if ( ! empty( $filter['exclude'] ) ) {
				$exclude  = array_flip( $filter['exclude'] );
				$children = array_values(
					array_filter( $children, fn( $c ) => ! isset( $exclude[ $c['slug'] ] ) )
				);
			}

			$item['children'] = $children;
			if ( $add_new_url ) {
				$item['addNewUrl'] = $add_new_url;
			}

			return $item;
		}, $items );
	}

	private function is_add_new_item( array $child ) {
		// Match by slug — covers core WP and CPTs.
		if ( strpos( $child['slug'], 'post-new.php' ) === 0 ) return true;
		if ( $child['slug'] === 'media-new.php' )              return true;
		if ( $child['slug'] === 'plugin-install.php' )         return true;
		return false;
	}

	/**
	 * Strip HTML and WP's notification count badges from a menu label.
	 * e.g. "Comments <span class='awaiting-mod'><span>5</span></span>" → "Comments"
	 */
	private function clean_label( $raw ) {
		// Iteratively remove innermost span tags (handles nesting).
		$cleaned = $raw;
		do {
			$prev    = $cleaned;
			$cleaned = preg_replace( '/<span\b[^>]*>[^<]*<\/span>/i', '', $cleaned );
		} while ( $cleaned !== $prev );
		return trim( wp_strip_all_tags( $cleaned ) );
	}

	private function resolve_url( $slug, $parent = '' ) {
		if ( filter_var( $slug, FILTER_VALIDATE_URL ) ) {
			return $slug;
		}
		if ( strpos( $slug, '.php' ) !== false ) {
			return admin_url( $slug );
		}
		return admin_url( 'admin.php?page=' . $slug );
	}

	private function get_config() {
		// Allow a theme or host to ship their own nav-config.json.
		$theme_config = get_template_directory() . '/nav-config.json';
		$config_path  = file_exists( $theme_config )
			? $theme_config
			: plugin_dir_path( __FILE__ ) . 'nav-config.json';

		if ( ! file_exists( $config_path ) ) {
			return [];
		}

		$decoded = json_decode( file_get_contents( $config_path ), true );
		return is_array( $decoded ) ? $decoded : [];
	}
}

new WP_Navigation();
